### ISSUE TITLE
Allow for different address and port for Geth

### ISSUE THREAD

**Issue by TMLutas** [5he11/RelexDistributor#1]
Instead of hard coding an address, give a prompt for the address and port and if you just hit enter, you use the default of 127.0.0.1:8545

**Comment by 5he11** [comment]
This was coded this way on purpose because the real user of this application do NOT understand much technical details such as how can a local node bind to a different interface rather than 127.0.0.1, the same applies to the port. Allowing them to change this behavior is not valuable and sometime even causes more trouble.
