### ISSUE TITLE
What if the source account has too little ethereum? 

### ISSUE THREAD

**Issue by TMLutas** [5he11/RelexDistributor#3]
This is current version line 92
var gas = await function.EstimateGasAsync(from, null, null, to, amountInEthereumFormat);

In a robust implementation, we probably want to be able to do a test run that doesn't actually do transactions but just adds up the Ethereum amounts needed so that we can make sure that the account has enough to fund the gas needed. We also probably want to be able to adjust gas amounts off of the machine recommendation as a program parameter.

**Comment by 5he11** [comment]
It doesn't if we make a test run or not - the result will both be the same. In this case, the current implementation sends the transfer requests to Ethereum and it will be rejected immediately after submitting of this request so this request ends up with "Failed!".
Even if we implement a check/test on balance, we would still end up saying "Failed!" - there is no difference.

**Comment by TMLutas** [comment]
The amount of Ether we need to deposit in the account to do a transfer is going to be something that we want to know before we actually do transfers.

**Comment by 5he11** [comment]
Good catch! I will see if I can estimate this before sending the requests.

**Comment by 5he11** [comment]
An investigation have done on this matter but it turned out that we can only technically estimate how much gas is needed for making a transaction, but we cannot technically "know" the market price of gas because it's driven by the market itself rather than the blockchain.
So I think we have no way to implement this unless the application "watches" gas market.
