### ISSUE TITLE
Insufficient comment

### ISSUE THREAD

**Issue by TMLutas** [5he11/RelexDistributor#4]
Here are lines 84 and 85 of the current version
                //the real transactional amount needs to be multiplied by the decimals of Relex Token
                amount *= (long)Math.Pow(10, RelexDecimals);

For someone who is not that familiar (it's been a long time since I had anything to do with C of any variant), you probably want a little more detail explaining what you are doing here. Why must the stated transactional amount need to be modified?

**Comment by 5he11** [comment]
Thank for your input on this. Do you have a better way to explain this? Just make the change and request for a pull-request.

**Comment by TMLutas** [comment]
I don't understand what you're doing there. If I understood what you were doing, I'd have suggested a better comment.

**Comment by 5he11** [comment]
I think it's quite clear and very enough for anyone who is familiar with Ethereum by saying "the real transactional amount needs to be multiplied by the decimals of Relex Token".
If someone who doesn't have basic Ethereum background, this person needs to learn them first in order to develop applications interacting with Ethereum.
I wrote these comments in a context that assumes readers already have these knowledge, otherwise I will need to write a lot of unnecessary info that can be found easily by just googling.

In this case, the background is at here https://theethereum.wiki/w/index.php/Natural_Units
